services:
  server:
    ports:
      - '13001:3001'

  realtime-server:
    ports:
      - '13002:3002'

  web-customer:
    ports:
      - '18080:3000'
    environment:
      NEXT_PUBLIC_SITE_URL: http://localhost:18080
      NEXT_PUBLIC_SOCKET_URL: http://localhost:13002

  web-admin:
    ports:
      - '18081:3000'
    environment:
      NEXT_PUBLIC_SITE_URL: http://localhost:18081
      NEXT_PUBLIC_SOCKET_URL: http://localhost:13002

  web-driver:
    ports:
      - '18082:3000'
    environment:
      NEXT_PUBLIC_SITE_URL: http://localhost:18082
      NEXT_PUBLIC_SOCKET_URL: http://localhost:13002

  web-merchant:
    ports:
      - '18083:3000'
    environment:
      NEXT_PUBLIC_SITE_URL: http://localhost:18083
      NEXT_PUBLIC_SOCKET_URL: http://localhost:13002

  caddy:
    profiles:
      - ec2
